# Generated by Django 4.1.5 on 2023-01-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bassett', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='active',
        ),
    ]
