# Generated by Django 4.1.5 on 2023-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bassett', '0002_remove_team_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='valid_locations',
            field=models.ManyToManyField(to='bassett.location'),
        ),
        migrations.DeleteModel(
            name='SportLocation',
        ),
    ]
