# Generated by Django 4.1.5 on 2023-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bassett', '0004_team_losses_team_wins_alter_game_score1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='color1',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='black', max_length=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='color2',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='white', max_length=7),
        ),
    ]
