"""
Django settings for eli project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4f46d68(na*#h(10vu_0k=(anbb3cr!@29feh)5f_b^ag^bdy8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'apps.owls.plus']
CSRF_TRUSTED_ORIGINS = ['https://*.owls.plus:9202', 'https://*.owls.plus:9203', 'https://*.127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'bassett',
    'accounts',
]

# make sure the domains are lowercase; these are the domains that can be used in this system
DOMAIN_LIST = ["taylor.edu", "campus.tayloru.edu"]

GRAPH_MODELS = {
    'app_labels': ['bassett', 'accounts'],
    'group_models': True, # include this if you want the apps in their groupings
}

ADMINS = [
    ('Matthew', 'matt_getgen@taylor.edu'),
    ('Eli', 'eli_bassett@taylor.edu'),
]

MANAGERS = ADMINS
SERVER_EMAIL = 'chr_update@owls.technology'
EMAIL_HOST = 'smtp.readyhosting.com'
EMAIL_HOST_USER = 'intramural_president@owls.technology'
EMAIL_HOST_PASSWORD = 'ItIsSoFun2PlayHopScotch!'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eli.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'eli/templates'),
            os.path.join(BASE_DIR, 'bassett/templates'),
            os.path.join(BASE_DIR, 'accounts/templates'), # Customize User
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eli.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bassett',
        'USER': 'doris',
        'PASSWORD': 'QingJingChung',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
# TIME_ZONE = 'EST' # time also needs to be set in database
# TIME_ZONE = 'America/New_York'  # time also needs to be set in database America/New_York # NOT WORKING :-(
USE_I18N = True
USE_TZ = True

# Gender Choices -- used across the accounts and bassett
HUMAN_GENDER_CHOICES = [
    ('female','Female'),
    ('male', 'Male'),
]

LEAGUE_GENDER_CHOICES = []
for gender in HUMAN_GENDER_CHOICES:
    LEAGUE_GENDER_CHOICES.append(gender)
LEAGUE_GENDER_CHOICES.append(('coed', 'Co-Ed'))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = "accounts.CustomUser"  # Customize User
AUTH_USER_MODEL = 'accounts.UserProfile'
